select_list: select_item ("," select_item)*

select_item: select_value
    | select_value alias
    | STAR

STAR: "*"

!?select_value: CNAME
    | FUNCTION "(" arg_list ")"

alias: CNAME
    | AS CNAME

arg_list: arg_item ("," arg_item)*

!?arg_item: DATE_INTERVAL
    | TIME_INTERVAL
    | FUNCTION "(" arg_list ")"
    | CNAME

DATE_INTERVAL: "MONTH"i
    | "WEEK"i

TIME_INTERVAL: "MINUTE"i
    | "SECOND"i


AS: "AS"i
FUNCTION: CNAME


%import common.CNAME
